Blog/Blog/Controllers/EtiketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    using Models;
    public class EtiketController : Controller
    {
        // GET: Etiket
        blog_iozContext context = new blog_iozContext();
        public ActionResult Index(int id)
        {
            return View(id);
        }
        public PartialViewResult EtiketlerWidget()
        {
            return PartialView(context.Etikets.ToList());
        }
        public ActionResult MakaleListele(int id)
        {
            var data = context.Makales.Where(x => x.Etikets.Any(y => y.EtiketId == id)).ToList();
            return View("MakaleListeleWidget", data);
        }
    }
}

Blog/Blog/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    using Models;
    public class KategoriController : Controller
    {
        // GET: Kategori
        blog_iozContext context = new blog_iozContext();
        public ActionResult Index(int id)
        {
            return View(id);
        }
        public PartialViewResult KategoriWidget()
        {
            return PartialView(context.Kategoris.ToList());
        }
        public ActionResult MakaleListele(int id)
        {
            var data = context.Makales.Where(x=>x.KategoriID==id).ToList();
            return View("MakaleListeleWidget", data);
        }
    }
}

Blog/Blog/Views/Shared/Arama.cshtml
@{ 
    Layout = null;
}
<div class="sidebox widget">
    <h3 class="widget-title section-title">Ara</h3>
    <form class="searchform" action="/Home/Ara" method="post">
        <label><i class="icon-search"></i></label>
        <input type="text" id="s2" name="content" value="Birşeyler Ara" onfocus="this.value=''" onblur="this.value='Birşeyler Ara'" />
        <button type="submit" class="btn">Ara</button>
    </form>
</div>

Blog/Blog/Views/Shared/MakaleListeleWidget.cshtml
@{ 
    Layout = null;
}
<script src="~/Content/style/js/jquery.min.js"></script>
<script>
    $(document).ready(function myfunction() {
        $("a.begen").click(function myfunction() {
            var id = $(this).data("id");
           
            var link = "/Makale/Begen/" + id;
            $.ajax({
                type: "GET",
                url: link,
                success: function myfunction(result) 
            {
                    $("a.begen").html(result);
            }
            });
        });
    });
</script>

@model IEnumerable<Blog.Models.Makale>

@helper IcerikKisalt(string icerik)
{
if (icerik.Length > 300)
{
        @icerik.Substring(0, 300);
}
else
{
        @icerik;
}
}
<div class="blog-posts col-blog">
    @foreach (Blog.Models.Makale mkl in Model)
    {
        <div class="post row">
            <div class="col-sm-4">
                <figure>
                    <a href="/Makale/Detay/@mkl.MakaleId">
                        <div class="text-overlay">
                            <div class="info"><span>Hepsini Oku</span></div>
                        </div>
                        <img src="@mkl.Resim.OrtaBoyut" alt="" />
                    </a>
                </figure>
            </div>
            <div class="col-sm-8 post-content">
                <div class="meta"><span class="date">@mkl.EklenmeTarihi.ToShortDateString()</span>
                <span class="comments"><a href="#">@mkl.Yorums.Count <i class="icon-chat-1"></i></a></span>
                @if (User.Identity.IsAuthenticated)
                {
                    <span>
                        <a class="begen" href="javascript:void(0)" data-id="@mkl.MakaleId">
                            @mkl.BegeniSayisi
                        </a>
                        <img src="/Content/images/like.png" />
                    </span>
                }
                
                <span><a href="#">
    @mkl.GorontulenmeSayisi
    <img src="/Content/images/view.png" />
</a></span>
                </div>
                <h2 class="post-title"><a href="/Makale/Detay/@mkl.MakaleId">@mkl.Baslik</a></h2>
                <p>@IcerikKisalt(mkl.Icerik)</p>
            </div>
        </div>
    }
    
</div>

Blog/Blog/Views/Shared/SiteHakkinda.cshtml
<div class="sidebox widget">
    <h3 class="widget-title section-title">C# Ustası</h3>
    <p>Her türlüC# programlama işleri itina ile yapılır.</p>
    <ul class="social">
        <li><a href="#"><i class="icon-s-rss"></i></a></li>
        <li><a href="#"><i class="icon-s-twitter"></i></a></li>
        <li><a href="#"><i class="icon-s-facebook"></i></a></li>
        <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
        <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
        <li><a href="#"><i class="icon-s-dribbble"></i></a></li>
        <li><a href="#"><i class="icon-s-flickr"></i></a></li>
    </ul>
    <div class="clearfix"></div>
</div>

Blog/Blog/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/Content/style/images/favicon.png">
    <title>cnr Blog-@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->
    <link href="/Content/style/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/style/css/plugins.css" rel="stylesheet">
    <link href="/Content/style.css" rel="stylesheet">
    <link href="/Content/style/css/color/red.css" rel="stylesheet">
    <link href="/Content/style/type/bebas.css" rel="stylesheet">
    <link href="/Content/style/type/fontello.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="/Content/style/js/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
          <![endif]-->
    @RenderSection("head", false)
</head>
<body>
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
    <div class="body-wrapper">
        <div class="navbar default">
            <div class="navbar-header">
                <div class="container">
                    <div class="basic-wrapper">
                        <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i></i></a>
                        <div class="navbar-brand"><a href="index.html"><img src="/Content/style/images/logo.png" alt="" data-src="/Content/style/images/logo.png" data-ret="style/images/logo@2x.png" class="retina" /></a></div>
                    </div>
                    <nav class="collapse navbar-collapse pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="/Home/Index">Anasayfa</a></li>
                            @if (User.IsInRole("Yazar"))
                            {
                                <li class="current dropdown">
                                    <a href="/Yazar/Index" class="dropdown-toggle js-activated">Yazar Paneli</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="/Makale/Ekle">Makale Ekle</a></li>
                                        <li><a href="/Yazar/Takipcileri">Takipçilerim</a></li>
                                        <li><a href="/Yazar/Makalelerim">Makalelerim</a></li>

                                    </ul>
                                </li>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                            <li class="dropdown">
                                <a href="/Admin/Index" class="dropdown-toggle js-activated">Admin Panel</a>
                                <ul class="dropdown-menu">
                                    <li><a href="/Makale/MakaleEkle">Makale Ekle</a></li>
                                    <li><a href="/Kategori/KategoriEkle">Kategori Ekle</a></li>
                                    <li><a href="/Etiket/EtiketEkle">Etiket Ekle</a></li>
                                    <li><a href="/Admin/RolEkle">Rol Ekle</a></li>
                                    <li><a href="/Admin/KullaniciEkle">Kullanıcı Ekle</a></li>
                                    <li><a href="/Admin/YazarOnaylari">Yazar Onayları</a></li>
                                </ul>
                            </li> 
                            }
                            @if (!User.IsInRole("Yazar") || !User.Identity.IsAuthenticated|| !User.IsInRole("Admin"))
                            {
                                <li>
                                    <a href="/Yazar/YazarOl" >Yazar Ol</a>
                                </li>
                            }
                            
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a href="/Kullanici/UyeOl" >Üye Ol</a>
                                </li>
                            }
                            
                            @if (User.Identity.IsAuthenticated)
                            {
                            <li><a href="/Kullanici/CikisYap?redirectUrl=@this.Request.RawUrl">Çıkış Yap</a></li>
                            }
                            else
                            {
                                <li><a href="/Kullanici/GirisYap">Giriş Yap</a></li>
                            }

                            <li class="dropdown social-dropdown pull-right">
                                <div class="share btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="icon-heart-1"></i></div>
                                <ul class="button-group dropdown-menu dropdown-menu-right share-links">
                                    <li><a href="#" class="btn"><i class="icon-s-facebook"></i></a></li>
                                    <li><a href="#" class="btn"><i class="icon-s-twitter"></i></a></li>
                                    <li><a href="#" class="btn"><i class="icon-s-pinterest"></i></a></li>
                                </ul>
                            </li>
                            <!--/social-dropdown -->
                        </ul>
                        <!--/.navbar-nav -->
                    </nav>
                    <!--/.nav-collapse -->
                </div>
                <!--/.container -->
            </div>
            <!--/.navbar-header -->
        </div>
        <!--/.navbar -->
        <div class="offset"></div>
        <div class="dark-wrapper page-title">
            <div class="container inner">
                <h1> Our Journal </h1>
            </div>
            <!--/.container -->
        </div>
        <!--/.page-title -->

        <div class="container inner">
            <div class="row">
                <div class="col-sm-8 content">
                    @RenderBody()
                </div>
                <!-- /.content -->
                <aside class="col-sm-4 sidebar lp30">
                    @{
                        Html.RenderAction("PopularMakalelerWidget", "Home");
                    }
                    <!-- /.widget -->
                    @{
                        Html.RenderPartial("SiteHakkinda");
                    }
                    <!-- /.widget -->
                    @{
                        Html.RenderPartial("Arama");
                    }
                    <!-- /.widget -->
                    
                    <!-- /.widget -->
                    @{
                        Html.RenderAction("KategoriWidget", "Kategori");
                    }
                    <!-- /.widget -->
                    @{
                        Html.RenderAction("EtiketlerWidget", "Etiket");
                    }
                    <!-- /.widget -->
                </aside>
                <!-- /.col-sm-4 .sidebar -->

            </div>
            <!-- /.row -->
        </div>
        <!--/.container -->
        <footer class="footer black-wrapper">
            <div class="container inner">
                <div class="row">

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Popular Posts</h3>
                            <ul class="post-list">
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a1.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Magna Mollis Ultricies</a></h5>
                                        <em>3th Oct 2012 <span class="comments"><a href="#">8 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a2.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Ornare Nullam Risus</a></h5>
                                        <em>28th Sep 2012 <span class="comments"><a href="#">5 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a3.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Euismod Nullam</a></h5>
                                        <em>15th Aug 2012 <span class="comments"><a href="#">9 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                            </ul>
                            <!-- /.post-list -->
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">About Us</h3>
                            <p>Aenean lacinia bibendum nulla sed leo posuere erat a ante venenatis dapibus posuere velit aliquet. Donec ullamcorper metus auctor fringi. Nullam quis risus. </p>
                            <p>Vestibulum id ligula porta  euismod semper. Maecenas faucibus mollis.</p>
                            <div class="divide5"></div>
                            <ul class="social">
                                <li><a href="#"><i class="icon-s-rss"></i></a></li>
                                <li><a href="#"><i class="icon-s-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-s-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
                                <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Get In Touch</h3>
                            <p>Fusce dapibus, tellus commodo, tortor mauris condimentum utellus fermentum, porta sem malesuada magna. Sed posuere consectetur est at lobortis.</p>
                            <div class="contact-info">
                                <i class="icon-location"></i> Moonshine St. 14/05 Light City <br />
                                <i class="icon-phone"></i>+00 (123) 456 78 90 <br />
                                <i class="icon-mobile"></i>+80 (547) 455 47 54 <br />
                                <i class="icon-mail"></i> <a href="first.last%40email.html">first.last@email.com</a>
                            </div>
                        </div>
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h4 class="widget-title">Tags</h4>
                            <ul class="tag-list">
                                <li><a href="#">Web</a></li>
                                <li><a href="#">Photography</a></li>
                                <li><a href="#">Illustation</a></li>
                                <li><a href="#">Fun</a></li>
                                <li><a href="#">Blog</a></li>
                            </ul>
                            <!-- /.tag-list -->
                        </div>
                        <!-- /.widget -->

                        <div class="widget">
                            <h4 class="widget-title">Categories</h4>
                            <ul class="circled">
                                <li><a href="#">Web Design (21)</a></li>
                                <li><a href="#">Photography (19)</a></li>
                                <li><a href="#">Graphic Design (16)</a></li>
                            </ul>
                        </div>
                        <!-- /.widget -->

                    </div>
                    <!-- /column -->

                </div>
                <!-- /.row -->
            </div>
            <!-- .container -->

            <div class="sub-footer">
                <div class="container">
                    <p class="pull-left">© 2015 Keepsake. All rights reserved. Theme by <a href="http://elemisfreebies.com/">elemis</a>.</p>
                    <ul class="footer-menu pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- /footer -->
    </div>
    <!--/.body-wrapper -->
    <script src="/Content/style/js/jquery.min.js"></script>
    <script src="/Content/style/js/bootstrap.min.js"></script>
    <script src="/Content/style/js/plugins.js"></script>
    <script src="/Content/style/js/scripts.js"></script>
</body>
</html>